### ISSUE TITLE
Fail to build on Pi4

### ISSUE THREAD

**Issue by Exarkuniv** [stefanhendriks/Dune-II---The-Maker#200]
not sure if it can or not. 
im running Debian-buster 
i have cmake libsdl1.2-dev cmake-curses-gui g++ liballegro5-dev libxft-dev installed

i have used 
git clone to get your software and i did 
mkdir build
  cd build
  
 cmake ..
 
 make 

and i get 
[  4%] Building CXX object CMakeFiles/d2tm.dir/cGame_draw.cpp.o
In file included from /home/pi/RetroPie-Setup/tmp/build/dmaker/include/d2tmh.h:14,
                 from /home/pi/RetroPie-Setup/tmp/build/dmaker/ai.cpp:12:
/home/pi/RetroPie-Setup/tmp/build/dmaker/include/allegroh.h:30:10: fatal error: alfont.h: No such file or directory
 #include <alfont.h>
          ^~~~~~~~~~
compilation terminated.
In file included from /home/pi/RetroPie-Setup/tmp/build/dmaker/include/d2tmh.h:14,
                 from /home/pi/RetroPie-Setup/tmp/build/dmaker/cGame_draw.cpp:1 :
/home/pi/RetroPie-Setup/tmp/build/dmaker/include/allegroh.h:30:10: fatal error: alfont.h: No such file or directory
 #include <alfont.h>
          ^~~~~~~~~~
make[2]: *** [CMakeFiles/d2tm.dir/build.make:63: CMakeFiles/d2tm.dir/ai.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
compilation terminated.
make[2]: *** [CMakeFiles/d2tm.dir/build.make:89: CMakeFiles/d2tm.dir/cGame_draw.cpp.o] Error 1
In file included from /home/pi/RetroPie-Setup/tmp/build/dmaker/building/../include/d2tmh.h:14,
                 from /home/pi/RetroPie-Setup/tmp/build/dmaker/building/cItemBuilder.cpp:1:
/home/pi/RetroPie-Setup/tmp/build/dmaker/building/../include/allegroh.h:30:10: fatal error: alfont.h: No such file or directory
 #include <alfont.h>
          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/d2tm.dir/build.make:76: CMakeFiles/d2tm.dir/building/cItemBuilder.cpp.o] Error 1
In file included from /home/pi/RetroPie-Setup/tmp/build/dmaker/include/d2tmh.h:14,
                 from /home/pi/RetroPie-Setup/tmp/build/dmaker/cGame_logic.cpp:22:
/home/pi/RetroPie-Setup/tmp/build/dmaker/include/allegroh.h:30:10: fatal error: alfont.h: No such file or directory
 #include <alfont.h>
          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/d2tm.dir/build.make:102: CMakeFiles/d2tm.dir/cGame_logic.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/d2tm.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

any thoughts on what im missing here?

thanks for anyhelp

**Comment by stefanhendriks** [comment]
2 things I notice:

1. You use allegro 5, but d2tm uses 4.2. The binaries of allegro are in the repo. Not sure if it works on debian though.

2. There seems to be a problem finding dependency/header files. You could copy over the header files into your gcc/mingw include dir. Along with the allegro.a file (and others, alfont.a , etc). 

I wish to migrate away from Allegro but that wont be any time soon.

**Comment by Exarkuniv** [comment]
I'll give it a shot with manually install 4.2 and moving the files that it can't find. 

I'll let you know what I figure out. 
If it works cool. Of not. Well it was worth a shot. 
Your work looks amazing

**Comment by Exarkuniv** [comment]
so i have gotten time to dig around with looking, seems that on the Raspberry pie i dont have a gcc/mingw folder. i did 'install' mingw that was on the debian destro but it does not look like that was the right on. so i think right now it will be a no on getting it installed

**Comment by stefanhendriks** [comment]
I think with debian you will need gcc. But I'm not sure. I still want to figure that out some day.

I think once I solve that it will be easier for you as well.

Unless you like digging into this, I'll try to help as much as possible.

Also, you need cmake.

**Comment by Exarkuniv** [comment]
I do have gcc and cmake install. 
i will do more looking on where on the Pi gcc install and i will try putting what you told me to in there. 

im not the most knowledgeable  when it comes to linux. i know just enough to be able to complie things and to some trouble shooting on when things dont work

**Comment by stefanhendriks** [comment]
> im not the most knowledgeable when it comes to linux. i know just enough to be able to complie things and to some trouble shooting on when things dont work

That makes two of us ;-).

It has been a while. But if I remember correctly you need to copy over the header files (from https://github.com/stefanhendriks/Dune-II---The-Maker/tree/master/dependencies/allegro and https://github.com/stefanhendriks/Dune-II---The-Maker/tree/master/dependencies/mingw32/include (unpack zip file)) into your gcc include dir. *or* you should point to them in your build. The `CMakeList.txt` (https://github.com/stefanhendriks/Dune-II---The-Maker/blob/master/CMakeLists.txt) file does not reference these library files. And I have no idea how to do that in a friendly manner (ie, so that it will work just by checking out the code).

So, what I have is a `C:\dev\MinGW32\include` folder, and I put all the include/header files into there (so I have a `include\allegro` folder as well). I also put the library files in the `c:\dev\MinGW32\lib` dir. There are precompiled versions at https://github.com/stefanhendriks/Dune-II---The-Maker/tree/master/lib - but I don't see any linux ones :(

See also: https://github.com/stefanhendriks/Dune-II---The-Maker/blob/master/dependencies/mingw32/howto.txt for some clues.

If all else fails, then I should pick up #57 after releasing 0.6.0

**Comment by Exarkuniv** [comment]
so me copying it like you said did nothing. 
but when i moved the files in allergro folder into the include folder in the root of your git and i was able to get just a bit more

here is the [error](https://pastebin.com/c8puEWBd) log

if i was a betting man i think it has to deal with MinGW32 not being installed on the pie. and i have not found anything on how to so that. and the link in the howto.txt is dead

**Comment by stefanhendriks** [comment]
Thx for reporting back. I think you're correct. If you can find a way to install mingw on the pie it might get you further.

Another way would be to use wine? (If that is on the pie?)

**Comment by Exarkuniv** [comment]
yes there is wine on the Pi. and i do have the arm version installed so i can play diablo 2 on my pi.
i will play around with that. have not used it ( other then diablo2) and see what i can get going

**Comment by Exarkuniv** [comment]
so i was able to get ming32 to install, but its not called "mingw"
these are what i was able to get installed easyly
/usr/i686-w64-mingw32/include/crtdefs.h
/usr/x86_64-w64-mingw32/include/crtdefs.h
/usr/share/mingw-w64/include/crtdefs.h

is there a way for me to link the CMakeList.txt to use these? or whatever looks for the mingw

**Comment by stefanhendriks** [comment]
I think we talk about the same thing, look at your folders , it has the `mingw32` in them. Regardless; next step would be to have cmake? If you already have it, perhaps [this SO answer helps](https://stackoverflow.com/questions/51509173/how-can-i-make-cmake-use-mingw-w64-gcc-g). It seems you can create a makefile out of `CMakeList.txt` with a certain flag so it uses mingw's `g++` .

Also, remember I talked about the `include` folder in some comments above? I believe that should be put into `/usr/x86_64-w64-mingw32/include/` (assuming your platform is x86)

**Comment by Exarkuniv** [comment]
thanks for all your help.  i was able to link it to the g++ that i have on the Pi
it seems to work longer but i get a bunch of errors 

this is only a small part of the error log
/home/pi/RetroPie-Setup/tmp/build/dmaker/include/_mingw.h:271:2: error: #error Only Win32 target is supported!
 #error Only Win32 target is supported!
  ^~~~~
In file included from /home/pi/RetroPie-Setup/tmp/build/dmaker/include/system.h:25,
                 from /home/pi/RetroPie-Setup/tmp/build/dmaker/include/d2tmh.h:13,
                 from /home/pi/RetroPie-Setup/tmp/build/dmaker/ai.cpp:12:
/home/pi/RetroPie-Setup/tmp/build/dmaker/include/time.h:12:2: error: #error Only Win32 target is supported!
 #error Only Win32 target is supported!
  ^~~~~
In file included from /home/pi/RetroPie-Setup/tmp/build/dmaker/include/time.h:323,
                 from /home/pi/RetroPie-Setup/tmp/build/dmaker/include/system.h:25,
                 from /home/pi/RetroPie-Setup/tmp/build/dmaker/include/d2tmh.h:13,
                 from /home/pi/RetroPie-Setup/tmp/build/dmaker/ai.cpp:12:
/home/pi/RetroPie-Setup/tmp/build/dmaker/include/sys/timeb.h:12:2: error: #error Only Win32 target is supported!
 #error Only Win32 target is supported!

so ill say since the Pi is not a x86. it is not going to work. 
maybe if i cant get box86 and wine working ( some people have) it might work there

Again i want to thank you for trying to help me get this working.

**Comment by stefanhendriks** [comment]
Hmm. I dont think it is about x86, but rather about 32 vs 64 bits? Perhaps you can invoke mingw 32 bits one instead of the 64 bit one? Not sure how though. I guess there would be a mingw folder without -64 ?

**Comment by stefanhendriks** [comment]
A few quick searches on my phone:

[Here](https://stackoverflow.com/questions/18703526/error-only-win32-target-is-supported) and [here](https://unix.stackexchange.com/questions/329122/is-this-error-only-win32-target-is-supported-coming-from-wrong-cc1plus) are some pointers.

Second link is I think the most interesting.

**Comment by stefanhendriks** [comment]
Also looks like you might need to add a compiler flag `-win32` ? Not sure.

I'm curious if this helps. Please let me know how things go. I find this very interesting 😀

**Comment by Exarkuniv** [comment]
yeah im not sure. i know that Buster (my OS) is a 32bit OS. there are a few out there running 64bit on the Pi4. i have yet to mess with that. 

i wish i knew more about adding compiler flags and what not

**Comment by Exarkuniv** [comment]
it just seems that it just will not find any of the mingw files that are installed on my system,
every time i get a error. i find the missing file and move it into the include folder from your main folder and it will move on to the next error

so it seems the main issue is that cmake or make just will not see the Mingw software i already have

**Comment by stefanhendriks** [comment]
then I wonder if you're really calling the mingw compiler? The mingw compiler has its own include folder, it should atleast see those.

If you mean the compiler can't see the header files from the project, then I guess cmake hasn't ran properly. Unfortunately I don't know how to get it compiling from the command line either (I use CLion, which manages all the cmake stuff for me at the moment, which is fine for now until I'll figure out how to do it properly).

**Comment by Exarkuniv** [comment]
your guess is as good as mine. for most of the games that i compile i just run cmake and then make. 
i did install a different Mingw and after getting the missing files in the include folder i get this error

 __MATHCALL_NARROW (__MATHCALL_NAME (sub), __MATHCALL_REDIR_NAME (sub), 2);
                    ^~~~~~~~~~~~~~~
In file included from /home/pi/RetroPie-Setup/tmp/build/dmaker/include/base.h:4 ,
                 from /home/pi/RetroPie-Setup/tmp/build/dmaker/include/system.h:22,
                 from /home/pi/RetroPie-Setup/tmp/build/dmaker/include/d2tmh.h:13,
                 from /home/pi/RetroPie-Setup/tmp/build/dmaker/ai.cpp:12:
/home/pi/RetroPie-Setup/tmp/build/dmaker/include/allegro/alcompat.h:45:22: note: previous declaration ‘fixed fsub(fixed, fixed)’
       AL_ALIAS(fixed fsub(fixed x, fixed y), fixsub(x, y))
                      ^~~~
/home/pi/RetroPie-Setup/tmp/build/dmaker/include/internal/alconfig.h:138:49: note: in definition of macro ‘AL_ALIAS’
       static __attribute__((unused)) __inline__ DECL    \
                                                 ^~~~
/home/pi/RetroPie-Setup/tmp/build/dmaker/ai.cpp: In member function ‘cBuildingListItem* cAIPlayer::isUpgradingList(int, int) const’:
/home/pi/RetroPie-Setup/tmp/build/dmaker/ai.cpp:1547:9: error: ‘assert’ was not declared in this scope
         assert(false);
         ^~~~~~
/home/pi/RetroPie-Setup/tmp/build/dmaker/ai.cpp:1547:9: note: ‘assert’ is defined in header ‘<cassert>’; did you forget to ‘#include <cassert>’?
/home/pi/RetroPie-Setup/tmp/build/dmaker/ai.cpp:16:1:
+#include <cassert>

/home/pi/RetroPie-Setup/tmp/build/dmaker/ai.cpp:1547:9:
         assert(false);
         ^~~~~~
make[2]: *** [CMakeFiles/d2tm.dir/build.make:63: CMakeFiles/d2tm.dir/ai.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/d2tm.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by Exarkuniv** [comment]
i did find the game that i had to add a CXXFLAG

`CXXFLAGS=-fpermissive cmake ..`  is the command i needed to use. 
i did try that with -win32. 
no change

**Comment by stefanhendriks** [comment]
A google search tells me [someone else had this problem](https://github.com/LibreSprite/LibreSprite/issues/30) and fixed it with [this in the CMakeList.txt file](https://github.com/LibreSprite/LibreSprite/commit/c080abcee0a3bbbad59e5d001bd4a3bb02fd703a). Perhaps that does something for you?

**Comment by Exarkuniv** [comment]
if i understood cmake better maybe, lol but thats all way over my head.

there is alot more to the error im getting now. i just showed you the end part

[error](https://pastebin.com/wFm3rfg9)

**Comment by stefanhendriks** [comment]
I wonder, did you unpack https://github.com/stefanhendriks/Dune-II---The-Maker/tree/master/dependencies/mingw32/include in your mingw include dir?

**Comment by Exarkuniv** [comment]
yes.
since i have 3 different versions of mingw installed. i placed all the files i unpacked into each. and i still get the same error.

i think it has to do something with it not knowing where to look for mingw32 on my system. 
i just dont know how to tell it where to look. 

ugh. i do wish it was a little more straight forward, but thats why i dont do programming. i would be so lost.

**Comment by stefanhendriks** [comment]
Its a shame it didnt work out. It might be easier once I migrate away from Allegro I think.

**Comment by enthusi** [comment]
I also had that issue with allegro.h missing.
Setting up liballegro4-dev (instead of 5) helped but next issue was alfont.h missing right away.
gcc, linux, amd64 system:

allegroh.h:30:10: fatal error: alfont.h: No such file or directory

gcc version 9.3./ ubuntu 20.04

**Comment by stefanhendriks** [comment]
I've updated the readme which points to an include zip file which contains those header files. If you can copy those to your environments include dir, then it should be able to find them.

**Comment by Exarkuniv** [comment]
@enthusi hope you have better luck. for now i have moved on to getting a few other things working.

**Comment by enthusi** [comment]
Thanks, found no reference to the zip in the readme but found the 3rdparty zip in dependencies dir and copied those to the local include which is mentioned in cmake config anyway. I hope that's ok...?
But it now bails pretty early at:
include/allegro/platform/almsvc.h:20:13: fatal error: io.h: No such file or directory
Sorry for all this mess. Maybe I should wait till there is a GCC distribution/code available.
