### ISSUE TITLE
Fremen production stuck with two palaces

### ISSUE THREAD

**Issue by ivanpopelyshev** [stefanhendriks/Dune-II---The-Maker#313]
Subj. I'll try to reproduce it again.

**Comment by stefanhendriks** [comment]
Interesting. I do know in general build speeds are influenced by the amount of structures. Which actually should not happen with Palace anyway. Dune 2 limited amount of palaces to 1.

Regardless I am curious why this happens.

Also i assume you had enough power?

**Comment by ivanpopelyshev** [comment]
Enough power, and i repaired them both.

> Dune 2 limited amount of palaces to 1.

PC version allowed me to use several.

**Comment by stefanhendriks** [comment]
Afaik Dune 2 allows only one palace. Regardless, it should not happen ;-).

Could you reproduce this? Or was this a one-off?

**Comment by stefanhendriks** [comment]
I tried to reproduce it, with 2, later 3 palaces. I played skirmish against 1 AI (harkonnen). It did not happen. Fremen got produced as expected.

**Comment by ivanpopelyshev** [comment]
Can you point me to relevant places in code?

**Comment by stefanhendriks** [comment]
building stuff is done by the [cItemBuilder](https://github.com/stefanhendriks/Dune-II---The-Maker/blob/master/building/cItemBuilder.cpp) 

but that is used for all kinds of things (units, buildings, super weapons, etc). 

Its build speed is [influenced here](https://github.com/stefanhendriks/Dune-II---The-Maker/blob/master/building/cItemBuilder.cpp#L52)

And starting to build something [happens here](https://github.com/stefanhendriks/Dune-II---The-Maker/blob/master/sidebar/cSideBar.cpp#L116)

**Comment by stefanhendriks** [comment]
@ivanpopelyshev did you have any new insights?

**Comment by ivanpopelyshev** [comment]
Stale, closing for now, will try to reproduce some day again :)
