### ISSUE TITLE
https://www.dune2themaker.com/ doesn't connect.

### ISSUE THREAD

**Issue by antdude** [stefanhendriks/Dune-II---The-Maker#323]
From 2 different ISPs. :(

**Comment by stefanhendriks** [comment]
Can reproduce. It is a forward to https://dune2themaker.fundynamic.com

Looks like the forward is http only so I'll make that https as well.

Even better is switching around: do the actual website at https://www.dune2themaker.com and let the subdomain forward to this. That is for another time though.

**Comment by stefanhendriks** [comment]
I bought an ssl certificate and set up the forwarding service. Might take a while to pick up? I'll test it later.

**Comment by stefanhendriks** [comment]
Still doesnt work. I'll contact the hoster about this

**Comment by stefanhendriks** [comment]
Message sent to hoster. Awaiting response.

**Comment by stefanhendriks** [comment]
FYI: http://www.dune2themaker.com does forward correctly, this is about the https variant that does not work. (even with SSL enabled)

**Comment by stefanhendriks** [comment]
Got response from hoster. The hostger is aware but is unable to fix this problem within a short amount of time. They said they're working on this thing but to expect it to take months to fix. :/

**Comment by antdude** [comment]
:( Time for a new host?

**Comment by stefanhendriks** [comment]
No, better would be to have https://www.dune2themaker.com be the real website, and not being under https://dune2themaker.fundynamic.com :)

**Comment by antdude** [comment]
I meant your hostger.

**Comment by stefanhendriks** [comment]
I know, but the hoster is fine. I have many things hosted there, their forwarding service is lacking. But thats not a reason to move all my stuff now :)

**Comment by antdude** [comment]
Ah!

**Comment by antdude** [comment]
Hey! It works now. :D
