### ISSUE TITLE
Cannot initialize graphics mode error during startup

### ISSUE THREAD

**Issue by mareker80** [stefanhendriks/Dune-II---The-Maker#330]
I started the game. Played a bit. Quit. Left PC for some time (it went to standby), came back and this error occured.

Currently happens every time. I'll reboot and see if I can reproduce it/make it go away
[log.txt](https://github.com/stefanhendriks/Dune-II---The-Maker/files/7205863/log.txt)
![cannot_initialize](https://user-images.githubusercontent.com/91142828/134238558-d96572b4-44e5-4f89-8a07-210febcbc98d.png)

.

**Comment by megabyteag** [comment]
Same story

**Comment by mareker80** [comment]
After rebooting the issue persists.

**Comment by stefanhendriks** [comment]
Question: does running `windowed.bat` work?

**Comment by megabyteag** [comment]
> Question: does running `windowed.bat` work?

After running windowed.bat :
![image](https://user-images.githubusercontent.com/91179818/134311168-e1e85961-d3ea-40ea-8db0-77ad1037ad44.png)

**Comment by stefanhendriks** [comment]
See also #314

**Comment by megabyteag** [comment]
My native laptop resolution 1366x768.
I edited the game.ini file, entered my resolution there and ran d2tm.exe. 
The game has started. I tried to close and start again - it works.
But when I run windowed.bat, it still displays an error window.
Anyway I don't really need windowed mode, I'm happy that the game works.

**Comment by stefanhendriks** [comment]
Yes windowed mode at full-screen resolution usually fails.

I guess the default: 1920x1080 simply does not fit and the app fails.

I could improve upon that.

Good to know it is working for you. Enjoy!

**Comment by mareker80** [comment]
800x600 works for me as well (looks even nicer, as original resolution made everything very tiny). Interesting that it worked once.
My native is: 1280x1024

**Comment by stefanhendriks** [comment]
Closing in favor of #331
