### ISSUE TITLE
large concret Slab placing canceled if 1 slab is invalid.

### ISSUE THREAD

**Issue by arkahys** [stefanhendriks/Dune-II---The-Maker#357]
I used this in placement : for 3 slab near sand or rocks. loosing 1 slab, but more rapid than 1 by 1.
And this can't be done.

**Comment by stefanhendriks** [comment]
I did fix some stuff with slab placement in the upcoming 0.6.5, see also #263 , if this solves your case, please close this issue.

**Comment by stefanhendriks** [comment]
sorry, I meant #299

**Comment by arkahys** [comment]
sorry, don't see duplication
