### ISSUE TITLE
ornithopter are destructed by their own rocket.

### ISSUE THREAD

**Issue by arkahys** [stefanhendriks/Dune-II---The-Maker#361]
The problem is very clear when launching 8 orni (from starport) on a unprotected base.
They loose PV with their rocket and from others. and finally all die !
Make a distinction between a rocket targeting Air and Ground could resolve and balance problem (as all rocket from all units will hurt Air zone or ground zone )
But, if resovle this problem on orni  and the other one (bad targeting), as orni are already a little cheated (with original scripts), that will unbalance game.
then, they may be more expensive (and/or more long to build).

**Comment by stefanhendriks** [comment]
I believe I fixed this, but I'll make sure and check.

**Comment by stefanhendriks** [comment]
Checked it. This was not fixed :) - The air projectiles would only not damage the originator of the bullet. However, it would still do friendly fire. I made it now so that ornithopters will *not* damage friendly (same team) *air* units.

**Comment by stefanhendriks** [comment]
I don't know why I said it was fixed, because I checked and it was not... 

Anyhow, it should be fixed now.

**Comment by arkahys** [comment]
Even in the worst and in the bad God does his work. I wish you the best.
