### ISSUE TITLE
Old mouse cursor still drawn when going to options menu

### ISSUE THREAD

**Issue by pbomta** [stefanhendriks/Dune-II---The-Maker#434]
See? Two mouse cursors. :) 
![d2tm-mouse-cursor-shown](https://user-images.githubusercontent.com/13233624/152533257-f5314c47-c16a-40c7-b6f9-495148f80851.png)

**Comment by stefanhendriks** [comment]
I also noticed this.

Btw, FYI: when I test and it is in between versions I always create a ticket and assign the `playtesting` label.

This is so that when I create release notes this won't show up. A 'bug' is something that was found in the previous released version(s).

**Comment by pbomta** [comment]
> Btw, FYI: when I test and it is in between versions I always create a ticket and assign the `playtesting` label.

Oh, yes, that makes sense. I was already wondering how you handled this.
