### ISSUE TITLE
Crash on exit  -  Linux OS

### ISSUE THREAD

**Issue by Akatsuki57** [stefanhendriks/Dune-II---The-Maker#450]
Game crash when i click on exit.

![Capture d’écran_2022-02-15_12-55-41](https://user-images.githubusercontent.com/99535165/154057650-258cdefb-f170-45f0-91e0-41a3b4356fb9.png)

gdb tell  me it's came from alfont

```c++
    // Destroy font of Allegro FONT library
    alfont_destroy_font(game_font);
    alfont_destroy_font(bene_font);
```

I change this in 

```c++
    // Destroy font of Allegro FONT library
    // alfont_destroy_font(game_font);
    // alfont_destroy_font(bene_font);
```

No game crash

**Comment by stefanhendriks** [comment]
the `alfont_destroy_font` calls should be done at the proper moment. Needs investigation.

Also which branch do you use right now? As the linux compatibility branch still needs to be merged into `master`.
