### ISSUE TITLE
Proper order of bootstrapping d2tm so that we can read settings and startup flags with sane order

### ISSUE THREAD

**Issue by stefanhendriks** [stefanhendriks/Dune-II---The-Maker#466]
Currently, the way d2tm is bootstrapped is all messed up. 

It means that resource allocation != instantiating (which we do want). But it also means we set values directly into a global `game` class from startup params, but then later overwrite from ini files.

This means, that config/ini files supersede startup parameters.

However, I think startup parameters should superside ini files instead.

In abstract sense I think this should become the picture:

- read startup params
- read config file
- merge two together to determine 'configuration state'
- initialize game with this 'configuration state' (ie, create unique ptr for game at this point with config object as constructor input)
- proceed...

**Comment by Akatsuki57** [comment]
To do this, I'm going to build a third party class that will read command line options and store them in an internal map.
This map will contain the only options that we have analyzed.

Next, the program will read the ini files. After, I switch back to the options stored in the map.
The program continues as normal.

**Comment by stefanhendriks** [comment]
The PR make sure the program arguments override the config in `game.ini` which is expected behavior.
