### ISSUE TITLE
ubuntu - improve launch instructions

### ISSUE THREAD

**Issue by dreamcat4** [stefanhendriks/Dune-II---The-Maker#468]
Hello,
I just noticed that after compiling `d2tm` executable (on linux). That we need to launch it from the parent main repo root folder, like this:

```sh
build/d2tm -windowed
```

Because simply just launching it within it's own `build` folder as `./d2tm`. Will then emit a variety of obscure looking errors. This is not something specified so clearly in the main readme. And would be a nice addition.

Another missing check in the source code is looking for the presence of the `data/` subfolder. Before continuing to then try loading in game assets from within that folder.

Or you could argue that all the game assets `data/` folder should be copied and duplicated into the target folder. As a step of the building proccess. For further subsequent packaging steps etc. IDK

But ATM i just launch it from the parent folder. And that is fine by me. Just knowing that for new users. Not to have as much difficult to understand error messages

Another thing missing on linux is a working multi monitor support. Even when running in `-windowed` mode. But that's a different matters. So won't go into that one here

**Comment by stefanhendriks** [comment]
@dreamcat4 what kind of errors do you see? I can run it in fullscreen mode fine here. But I do know it is kind of wonky in Win 10 when using > 100% DPI.

**Comment by stefanhendriks** [comment]
As for a development process: I create a `bin` directory (by executing `create_release.bat`), then I simply use CLion and set my path to there to run against. 

This is obviously not clear for those who don't use CLion or anything like that. So that should be improved in the readme for sure.

**Comment by dreamcat4** [comment]
For the multi monitor thing? On linux? Oh it gets confused thinking the entire span of the X desktop (all monitors connected together canvas)... is just the 1 primary monitor.

So it then messes up the whole desktop, by setting the resolution (from game.ini) as 800x600 or whatever on the primary monitor. That got applied to the primary monitor (even in `-windowed` mode it seems?). At the same time... the 2nd monitor i have here is then set to 'disabled' (in Xorg), and it's output gets switched off.

So maybe in `-windowed` mode some code for setting the monitor mode should be bypassed? IDK. It is still a bit beyond my own understanding

**Comment by Akatsuki57** [comment]
> Another thing missing on linux is a working multi monitor support. Even when running in `-windowed` mode. But that's a different matters. So won't go into that one here

With the modern SDL2 library, it will be easier to modify the program to better manage the screens.

**Comment by stefanhendriks** [comment]
Good to verify presence. So we have two tickets: better feedback when program cannot launch *and* improve readme. I'll create tickets for both.

**Comment by stefanhendriks** [comment]
I have created 3 tickets to pick this up. I will close this ticket so we dont have duplications. All information is referenced so we know what is said when and where.
