### ISSUE TITLE
IA havester is not present 

### ISSUE THREAD

**Issue by Mira-Fr** [stefanhendriks/Dune-II---The-Maker#476]
As i tested some game mechanic, i see this.
IA has no harvester but have a refinery.
![800x600_0002](https://user-images.githubusercontent.com/99535165/154863998-1ac0f864-6098-4ddf-9744-e1e95f1988dc.png)

**Comment by stefanhendriks** [comment]
Oh that is interesting; the AI has a refinery but no harvester? hmm

**Comment by stefanhendriks** [comment]
any way to reproduce?
