### ISSUE TITLE
Check for required files and report back when things are missing instead of obscure error messages

### ISSUE THREAD

**Issue by stefanhendriks** [stefanhendriks/Dune-II---The-Maker#484]
From #468

**Comment by stefanhendriks** [comment]
@Akatsuki57 you said you'd like to do this, so I assigned this ticket to you 👍

**Comment by Akatsuki57** [comment]
I need to deport this string `"data/gfxaudio.dat"` used in `utils\cSoundPlayer.cpp` into `GamesLogics.cpp`
Can I deport this string using class constructor for passing the string ?

**Comment by Akatsuki57** [comment]
@stefanhendriks prototype of my work is on branch `feature/Check_required_files`
Shall I deport `"data/gfxaudio.dat"` into `GamesLogics.cpp` to close this feature ?
