### ISSUE TITLE
Mouse cursor 

### ISSUE THREAD

**Issue by st3rg** [stefanhendriks/Dune-II---The-Maker#499]
Hi, the mouse cursor disappears on menu load. edited the cfg file to change 
[mouse]
mouse_accel_factor=0

to another value but no luck as it refers to acceleration only.

**Comment by stefanhendriks** [comment]
Did you try https://github.com/stefanhendriks/Dune-II---The-Maker/wiki/FAQ#game-does-not-start-windows-10 ? (see steps about mouse dissapearing/not responding). Perhaps change resolution? Does that do anything?
