### ISSUE TITLE
Missing feature: Attack spice bloom

### ISSUE THREAD

**Issue by BarabasGitHub** [stefanhendriks/Dune-II---The-Maker#551]
In the original you could attack them (via attack ground option iirc) to make them explode. I didn't find that feature here, it's only possible when driving/walking on top of them?

**Comment by stefanhendriks** [comment]
When you select a unit, then hold `CTRL` you should be able to attack ground/spice blooms.

Can you plz verify?

**Comment by BarabasGitHub** [comment]
Yes that works! Sorry, the controls are not very obvious in this game.

**Comment by stefanhendriks** [comment]
No problem! Please see the [wiki](https://github.com/stefanhendriks/Dune-II---The-Maker/wiki) for more information.
