### ISSUE TITLE
One harvester left

### ISSUE THREAD

**Issue by itwhite81** [stefanhendriks/Dune-II---The-Maker#569]
When I've lost my last harvester in several games another is usually called from the magic reinforcements.  However, In several games this has not happened. Is there is a limit to the number that can be reinforced?

In one game i noticed "you are down to your last harvester" message and I didn't have one.  Perhaps a count of the number of harvesters is producing the wrong number somehow?  I wondered if a loaded carryall was killed,does that update the state of the loaded harvester?  In two of the games, my base was fairly well pinned between two opponents and the corner of the map(less than 1/4 of the map for 3 teams) - my space was limited and enemy turrets were within range of my harvesters & carryalls most of the time.  

Speaking of which, Is there a key modifier that I can use with a selection to "ONLY" select harvesters?  Any mouse movement when trying to select a harvester in a group of tanks usually selects the tanks.  This makes the harvester trickier to select (especially when using a touchpad).

**Comment by stefanhendriks** [comment]
hmm. I am not sure why this happens. There is no limit to reinforcements for harvesters, thats for sure.

Perhaps the Carryall with the harvester got shot down. 

There is no hot key to only select harvesters. Might be related to #318 this will fix it - by double clicking on a specific unit, it should select all units of that type within the screen.

**Comment by stefanhendriks** [comment]
I have fixed issues about reinforcing harvesters, and I have made a GH ticket for selecting for a specific unit type. So I will be closing this GH ticket. Thx for your contribution!

**Comment by stefanhendriks** [comment]
(see also #583 , #582)
