### ISSUE TITLE
Add way to force a unit to leave repair facility

### ISSUE THREAD

**Issue by dpiller** [stefanhendriks/Dune-II---The-Maker#576]
Hi,

I had an interesting deadlock.
My last harvester was in the repair building when I run out of money. 
So no harvester to work and no replacement as I did have one harvester. But was unable to release for harvesting as no money to fix it.

**Comment by stefanhendriks** [comment]
Hmm, so a way to fix this is to have a way to force the harvester to leave the repair facility.

**Comment by stefanhendriks** [comment]
Pressing `D` while having the repair facility selected will make the unit that is within it leave the building.
