### ISSUE TITLE
Clip viewport rendering to game window dimensions

### ISSUE THREAD

**Issue by arjenvanderende** [stefanhendriks/Dune-II---The-Maker#73]
The viewport rendering (map tiles, units, etc) draws outside of the game window.
It's neater to use `set_clip_rect()` to draw exactly within the allowed bounds.

This also helps to get support at a later time to draw window-in-window.

**Comment by stefanhendriks** [comment]
#168 related?

**Comment by stefanhendriks** [comment]
@arjenvanderende afaik I understand this issue, it would mean we call `set_clip_rect()` before rendering battlefield (and everything on it) and then reset it back when rendering all other things.

Not sure if that is what you meant by that in 2020... if not, plz explain.
